"""baseline: users, feedback_events, audit_logs

Revision ID: 70ac64f3c673
Revises: 
Create Date: 2026-07-18 20:51:58.102309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (AutoString) referenced in the create_table ops


# revision identifiers, used by Alembic.
revision: str = '70ac64f3c673'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('image_source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_events_image_hash'), ['image_hash'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('twofa_secret', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('twofa_confirmed', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_events_image_hash'))

    op.drop_table('feedback_events')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
